# ccfe/backend/Dockerfile

FROM python:stretch
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
ADD . /code
WORKDIR /code
# CMD gunicorn -w 1 -b localhost:40001 --worker-class gevent app.app:app
CMD ["gunicorn", "-w", "5", "-b", "0.0.0.0:40001", "app.app:app"]
